name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Thanks for opening your first issue here! Be sure to follow the [bug](https://github.com/Griefed/ServerPackCreator/blob/1bbbfc59207e801068aa0f92ccd2869079fce7da/.github/ISSUE_TEMPLATE/bug-report.md), [feature](https://github.com/Griefed/ServerPackCreator/blob/1bbbfc59207e801068aa0f92ccd2869079fce7da/.github/ISSUE_TEMPLATE/feature-request.md), or [documentation](https://github.com/Griefed/ServerPackCreator/blob/1bbbfc59207e801068aa0f92ccd2869079fce7da/.github/ISSUE_TEMPLATE/documentation-request.md) issue templates!'
        pr-message: 'Thanks for opening this pull request! Be sure to follow the [pull request template](https://github.com/Griefed/ServerPackCreator/blob/1bbbfc59207e801068aa0f92ccd2869079fce7da/.github/ISSUE_TEMPLATE/pull_request.md)!'
