name: Test

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # SETUP JAVA AND GRADLE
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '8'
          check-latest: true
          cache: 'gradle'
      - name: Where is Java
        run: which java
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # BUILD AND TEST
      - name: Build with Gradle
        run: ./gradlew build --info --full-stacktrace

      # PUBLISH ARTIFACTS
      - uses: actions/upload-artifact@v3
        with:
          name: build-artifacts-gradle
          path: |
            build
          if-no-files-found: warn # 'warn' or 'ignore' are also available, defaults to `warn`